### ISSUE TITLE
Is it possible to access the published documents 

### ISSUE THREAD

**Issue by stigdefeyter** [lblod/app-gelinkt-notuleren#4]
I would like to inspect the published HTML documents which include the RDFa-tags . Could you enable this on the docker demo ? Thx

**Comment by madnificent** [comment]
Hi Stig.  Commit #282e04b publishes the publication frontend on port 81.  Pulling in the latest should solve this issue, closing this one.

You should be able to visit the entity of your choosing and check the published RDFa at that place.  Pick the notulen, they contain all needed information and RDFa.
