### ISSUE TITLE
Is it possible to access the documents for application profile "mandatendatabank"

### ISSUE THREAD

**Issue by stigdefeyter** [lblod/app-gelinkt-notuleren#5]
I would like to access the published HTML pages with an example of the applicationprofile "mandatendatabank" (http://data.vlaanderen.be/doc/applicatieprofiel/mandatendatabank/) in the "demo"-docker. How can I do that?

**Comment by madnificent** [comment]
Hi Stig,

The relevant portions of the mandatendatabank profile need to be
embedded in the published notulen.  Relevant information is therefore
published within these documents and no separate publishing is needed
from the notetaking system.

Kr,

Aad
